default_install_hook_types = ["pre-commit", "commit-msg"]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.0"
hooks = [
  { id = "ruff-check", args = ["--fix"] },
  { id = "ruff-format", args = ["--diff"] },
]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "v0.0.65"
hooks = [
  { id = "ty",
    always_run = false,
    args = [
      "--isolated",
      "--no-python-downloads",
      "--no-cache"
    ]
  }
]

[[repos]]
repo = "https://github.com/compilerla/conventional-pre-commit"
rev = "v4.4.0"
hooks = [
  {
    id = "conventional-pre-commit",
    stages = ["commit-msg"],
    args = [
      "--verbose",
      "--strict",
      "--force-scope",
      "chore",
      "docs",
      "feat",
      "fix",
      "refactor",
      "style",
      "test",
    ]
  }
]