# Programmatic DB connection from individual components.
dialect: ${oc.env:DB_DIALECT, postgresql}
driver: ${oc.env:DB_DRIVER, psycopg}
user: ${oc.env:DB_USER}
password: ${oc.env:DB_PASSWORD}
host: ${oc.env:DB_HOST}
port: ${oc.env:DB_PORT}
database: ${oc.env:DB_NAME, genreguru}
pool_size: 10
max_overflow: 20
echo: false
