name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    paths:
      - "**.py"
  pull_request:
    branches:
      - main
    paths:
        - "**.py"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: python setup
        uses: actions/setup-python@v7
        with:
          python-version-file: ".python-version"

      - name: uv install
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
          version: "0.12.0"

      - name: project install
        run: uv sync --all-extras --dev

      - name: Append to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/frontend" >> $GITHUB_ENV

      - name: build docs
        run: uv run pdoc -o docs/pdoc/ -d google --mermaid ./frontend/fingerprint_app/ ./frontend/genreguru_web/ ./src/genreguru/

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/pdoc/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
