name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses:  ytanikin/pr-conventional-commits@1.4.0
        with:
         task_types: '["chore","docs","feat","fix","refactor","style","test"]'
         custom_labels: '{"chore": "chore", "docs": "documentation", "feat": "feature", "fix": "fix", "refactor": "refactor", "style": "style", "test": "test"}'
         add_scope_label: 'true'
